# @author ssrjkk | cppload
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cppload-pro.fullname" . }}
  labels:
    {{- include "cppload-pro.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cppload-pro.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cppload-pro.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cppload-pro.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["cppload-cli"]
          args:
            - "--target"
            - {{ .Values.worker.loadTest.targetUrl | quote }}
            - "--rps"
            - {{ .Values.worker.loadTest.rps | quote }}
            - "--duration"
            - {{ .Values.worker.loadTest.duration | quote }}
          
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          
          env:
            {{- if .Values.metrics.enabled }}
            - name: PROMETHEUS_PORT
              value: {{ .Values.metrics.port | quote }}
            {{- end }}
            {{- if .Values.tracing.enabled }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.tracing.otlpEndpoint | quote }}
            - name: OTEL_SAMPLE_RATE
              value: {{ .Values.tracing.sampleRate | quote }}
            {{- end }}
          
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          
          {{- if .Values.metrics.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.metrics.path }}
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: {{ .Values.metrics.path }}
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
      
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}