# @author ssrjkk | volley
{{ if .Values.autoscaling.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "volley.fullname" . }}
  labels:
    {{- include "volley.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.autoscaling.minReplicas | default 2 }}
  selector:
    matchLabels:
      {{- include "volley.selectorLabels" . | nindent 6 }}
{{- end -}}
