{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cppload-pro.serviceAccountName" . }}
  labels:
    {{- include "cppload-pro.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
