# @author ssrjkk | volley
{{ if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "volley.serviceAccountName" . }}
  labels:
    {{- include "volley.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}