# @author ssrjkk | cppload
add_subdirectory(http_worker)

find_package(gRPC QUIET)
find_package(Protobuf QUIET)
if(CPLOAD_BUILD_GRPC_WORKER)
    if(NOT gRPC_FOUND)
        message(FATAL_ERROR "CPLOAD_BUILD_GRPC_WORKER=ON but gRPC not found")
    endif()
    if(NOT Protobuf_FOUND)
        message(FATAL_ERROR "CPLOAD_BUILD_GRPC_WORKER=ON but Protobuf not found")
    endif()
    add_subdirectory(grpc_worker)
elseif(gRPC_FOUND AND Protobuf_FOUND)
    add_subdirectory(grpc_worker)
endif()